---
Standards:
  -
    Title: Approaching a Problem
    Description: Breaking down a problem, Pseudocode, Pair Programming
    UID: pSGW3x
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: DkCHnM
        Path: /approaching-a-problem/pseudocode-and-logic.md
      -
        Type: Lesson
        UID: YUccLN
        Path: /approaching-a-problem/intro-to-pair-programming.md
  -
    Title: Intro to Debugging
    Description: Intro to Errors, Identifying Errors, Intro to Debugging
    UID: aGJLyn
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: amY0J6
        Path: /intro-to-debugging/intro-to-errors.md
      -
        Type: Lesson
        UID: B6OYlI
        Path: /intro-to-debugging/identifying-errors.md
      -
        Type: Lesson
        UID: VvrMFH
        Path: /intro-to-debugging/intro-to-debugging.md
  -
    Title: Intro to Dev Environment
    Description: Intro to Command Line
    UID: QkZshi
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: SxcEt0
        Path: /intro-to-dev-environment/intro-to-command-line.md
  -
    Title: Intro To Functions
    Description: Invoking and Defining Functions
    UID: e30a742083b7afa72ec565afafb9f64b
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8b4b8d39fd4f56926aa6181cb77ed45f
        Path: /intro-to-functions/functions-overview.md
      -
        Type: Lesson
        UID: 2a192a35477f1d52a01849d3b778609c
        Path: /intro-to-functions/invoking-functions.md
      -
        Type: Lesson
        UID: 692aeabdceb105d82aed2187db381860
        Path: /intro-to-functions/defining-functions.md
  -
    Title: Intro To Tests
    Description: Packages and Managing Packages, Automated Tests, Intro to pytest
    UID: cxnH0Z
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: abirop
        Path: /intro-to-tests/packages-and-managing-packages.md
      -
        Type: Lesson
        UID: qGalfB
        Path: /intro-to-tests/automated-tests.md
      -
        Type: Lesson
        UID: xGvLQz
        Path: /intro-to-tests/intro-to-pytest.md
