---
Standards:
  -
    Title: Intro To Functions
    Description: Invoking and Defining Functions
    UID: e30a742083b7afa72ec565afafb9f64b
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8b4b8d39fd4f56926aa6181cb77ed45f
        Path: /intro-to-functions/functions-overview.md
      -
        Type: Lesson
        UID: 2a192a35477f1d52a01849d3b778609c
        Path: /intro-to-functions/invoking-functions.md
      -
        Type: Lesson
        UID: 692aeabdceb105d82aed2187db381860
        Path: /intro-to-functions/defining-functions.md
  -
    Title: While Loops
    Description: Practice using while loops to loop while a conditional is true
    UID: wvsHzCRCSqu
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: vQjRO4
        Path: /while-loops/while-loops.md

