---
Standards:
  -
    Title: Ada Orientation
    Description: What is Ada?, Online Communcation Norms, Learn LMS, Slack, Google Calendar, Attendance, Project Feedback, One on Ones, Online Meeting Rooms, Retrospectives
    UID: sEk2C7
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 1o47Ox
        Path: /ada-orientation/what-is-ada.md
      -
        Type: Lesson
        UID: aKkd3p
        Path: /ada-orientation/online-communication-norms.md
      -
        Type: Lesson
        UID: FyXbJn
        Path: /ada-orientation/learn-lms.md
      -
        Type: Lesson
        UID: SdrsII
        Path: /ada-orientation/slack.md
      -
        Type: Lesson
        UID: 96fbha
        Path: /ada-orientation/google-calendar.md
      -
        Type: Lesson
        UID: xn8tqi
        Path: /ada-orientation/attendance.md
      -
        Type: Lesson
        UID: tj7R4n
        Path: /ada-orientation/project-feedback.md
      -
        Type: Lesson
        UID: Asf7p8
        Path: /ada-orientation/one-on-ones.md
      -
        Type: Lesson
        UID: tjHiWE
        Path: /ada-orientation/one-on-ones.instructor.md
      -
        Type: Lesson
        UID: O6okIU
        Path: /ada-orientation/online-meeting-rooms.md
      -
        Type: Lesson
        UID: 63F66B
        Path: /ada-orientation/retrospectives.md
  -
    Title: Approaching a Problem
    Description: Breaking down a problem, Pseudocode, Pair Programming
    UID: pSGW3x
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: DkCHnM
        Path: /approaching-a-problem/pseudocode-and-logic.md
      -
        Type: Lesson
        UID: YUccLN
        Path: /approaching-a-problem/intro-to-pair-programming.md
  -
    Title: Intro to Debugging
    Description: Intro to Errors, Identifying Errors, Intro to Debugging
    UID: aGJLyn
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: amY0J6
        Path: /intro-to-debugging/intro-to-errors.md
      -
        Type: Lesson
        UID: B6OYlI
        Path: /intro-to-debugging/identifying-errors.md
      -
        Type: Lesson
        UID: VvrMFH
        Path: /intro-to-debugging/intro-to-debugging.md
  -
    Title: Intro to Dev Environment
    Description: Intro to Command Line
    UID: QkZshi
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: SxcEt0
        Path: /intro-to-dev-environment/intro-to-command-line.md
  -
    Title: Intro To Functions
    Description: Functions Overview, Invoking Functions, Defining Functions
    UID: e30a742083b7afa72ec565afafb9f64b
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8b4b8d39fd4f56926aa6181cb77ed45f
        Path: /intro-to-functions/functions-overview.md
      -
        Type: Lesson
        UID: 2a192a35477f1d52a01849d3b778609c
        Path: /intro-to-functions/invoking-functions.md
      -
        Type: Lesson
        UID: 692aeabdceb105d82aed2187db381860
        Path: /intro-to-functions/defining-functions.md
  -
    Title: Intro To Tests
    Description: Packages and Managing Packages, Automated Tests, Intro to pytest
    UID: cxnH0Z
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: abirop
        Path: /intro-to-tests/packages-and-managing-packages.md
      -
        Type: Lesson
        UID: qGalfB
        Path: /intro-to-tests/automated-tests.md
      -
        Type: Lesson
        UID: xGvLQz
        Path: /intro-to-tests/intro-to-pytest.md
  -
    Title: Representing Data
    Description: Representing Data in Lists and Dictionaries, Data and JSON
    UID: hxB08H
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 88DgSp
        Path: /representing-data/representing-data-in-lists-and-dictionaries.md
      -
        Type: Lesson
        UID: r7MHqf
        Path: /representing-data/data-and-json.md
      -
        Type: Lesson
        UID: p4Pb0s
        Path: /representing-data/practice-representing-data.md
